In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mne.decoding import Vectorizer
from sklearn.preprocessing import MinMaxScaler
from mne.decoding import SPoC
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split as tts
import mne
from sklearn.model_selection import StratifiedKFold
from mne.datasets import sample
from mne.decoding import (SlidingEstimator, GeneralizingEstimator,
                          cross_val_multiscore, LinearModel, get_coef)
from sklearn.decomposition import PCA
from sklearn.decomposition import NMF
from sklearn.manifold import TSNE 
import os
from mne.decoding import UnsupervisedSpatialFilter
import os.path as op
from os import listdir
from os.path import isfile, join
from collections import defaultdict
from scipy.stats import skew, kurtosis
import mne 

from mne.decoding import Vectorizer
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.svm import SVC  # noqa
from sklearn.model_selection import ShuffleSplit  # noqa

from mne.decoding import UnsupervisedSpatialFilter
from sklearn.decomposition import PCA
from scipy.stats import skew, kurtosis
from sklearn.metrics import confusion_matrix
from mne.viz import tight_layout

import time
import pandas as pd

In [2]:
%run Batch_ArtifactFilter_Epoch.ipynb

In [3]:
epoch=remove_artifacts_and_create_epochs('C:\\USB Drive\\NewEEG-200s\\SA20140206\\20140206_1151.set')

hello
Reading C:\USB Drive\NewEEG-200s\SA20140206\20140206_1151.fdt
Reading 0 ... 831247  =      0.000 ...  1623.529 secs...
5977 events found
Event IDs: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  31 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 155 156 157 158 159 160 161 162 163 164 165]
time difference 1.80859375
[509034      0      4]
[509960      0    130]

 **1 bad trials dropped**
Setting up band-stop filter
Filter length of 3379 samples (6.600 sec) selected
Setting up band-pass filter from 5 - 1e+02 Hz
l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 25.0 Hz
Filter length of 845 samples (1.650 sec) selected
5977 events found
Event IDs: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  31 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 155 156 157 158 159 160 161 162 163 164 165]


[Parallel(n_jobs=10)]: Done  52 tasks      | elapsed:   45.1s
[Parallel(n_jobs=10)]: Done 129 out of 129 | elapsed:  1.2min finished


5584 events found
Event IDs: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  31 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 155 156 157 158 159 160 161 162 163 164 165]
Fitting ICA to data using 128 channels (please be patient, this may take a while)
Inferring max_pca_components from picks
Using all PCA components: 128
Fitting ICA took 120.5s.
    Searching for artifacts...
Artifact indices found:
    
Ready.
Transforming to ICA space (128 components)
Zeroing out 0 ICA components
1979 matching events found
Applying baseline correction (mode: mean)
Not setting metadata
0 projection items activated
Loading data for 1979 events and 500 original time points ...
1011 bad epochs dropped


In [17]:
def removebadchannel(epoch):
    epoch.drop_channels(['Lm','Rm','VEOG'])
    epoch.drop_channels(['STI 014'])

In [67]:
def findchanel (newdata, i,j):
    dataof50=[]
    k=0
    index=[]
    arrayofdata=[]
    sum1=[]
    sum2=[]
    for channel in newdata[j:j+10]:
        dataof50.append(channel)

    arrayofdata50=np.array(dataof50)
   # print(arrayofdata50.shape)
    for channel in arrayofdata50:
        sum1.append(np.sum(channel))
    sum1=np.array(sum1)
    #print("shape of channel sum : Xi", sum1.shape , sum1[0:3])
    mean1=np.sum(sum1)/125
    #print("mean of 125 channel: X",mean1)
    Dev=sum1-mean1
    #print("Xi-X",Dev.shape,Dev[0:3])
    SquareofDev=Dev*Dev
    #print("(Xi-X)^2",SquareofDev.shape,SquareofDev[0:3])
        ##print("variance",var1)
    sumofdev=np.sum(SquareofDev)
    #print("sum of (Xi-X)^2",sumofdev)
    var=sumofdev/125
    #print("variance",var)
    std=np.sqrt(var)
    #print("std",std)
    dis1=mean1-std
    dis2=mean1+std
    print(dis1,dis2)
    #print(arrayofdat3.shape)
    for k in range(len(sum1)):
        if sum1[k]<dis1 or sum1[k]>dis2 :
            sum2.append(sum1[k])
            index.append(k)
            arrayofdata.append(arrayofdata50[i])
            #print(arrayofdat3.shape)
    sum2=np.array(sum2)
    arrayofdata=np.array(arrayofdata)
    #print(sum2.shape)
    #print(index)
    print(arrayofdata.shape)
#     stdup=[dis1]*125
#     stddown=[dis2]*125
#     x=np.arange(0,125,1)
#     _=plt.plot(x,sum1)
#     _=plt.plot(x,stdup)
#     _=plt.plot(x,stddown)

In [68]:
findchanel (newdata, 0,1)

-0.002357696378399217 0.002425077811475986
(10, 125, 500)


In [36]:
 removebadchannel(epoch)

ValueError: Channel(s) Lm, Rm, VEOG not found, nothing dropped.

In [40]:
newdata=epoch.get_data()
epoch.get_data().shape

(968, 125, 500)

In [41]:
findchanel (newdata, 0,1)

(125, 500)
-0.0013672415665345727 0.0014172594877000255
(0,)
(1, 1, 500)
(2, 1, 500)
(3, 1, 500)
(4, 1, 500)
(5, 1, 500)
(6, 1, 500)
(7, 1, 500)
(8, 1, 500)
(9, 1, 500)
(10, 1, 500)
(11, 1, 500)
(12, 1, 500)
(13, 1, 500)
(14, 1, 500)
(15, 1, 500)
(16, 1, 500)
(17, 1, 500)
(18, 1, 500)
(19, 1, 500)
(20, 1, 500)
(21, 1, 500)
(22, 1, 500)
(23, 1, 500)
(24, 1, 500)
(25, 1, 500)
(26, 1, 500)
(27, 1, 500)
(28, 1, 500)
(29, 1, 500)
(30, 1, 500)
(31, 1, 500)
(32, 1, 500)
(33, 1, 500)
(34, 1, 500)
(34,)
[[1], [3], [11], [15], [17], [20], [26], [30], [31], [40], [42], [44], [45], [50], [51], [52], [61], [65], [70], [73], [74], [79], [81], [82], [88], [89], [90], [91], [96], [106], [114], [115], [119], [120]]
[[-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92079389e-06]
 [-3.92

In [196]:
def findchanel (newdata):
    arrays=[]
    for epochs in newdata:
        dataof50=[]
        sum1=[]
        sum2=[]
        index=[]
        k=0
        for channel in epochs:
            dataof50.append(channel)
        arrayofdata50=np.array(dataof50)
        for channel in arrayofdata50:
            sum1.append(np.sum(channel))
        arraysum1=np.array(sum1)
        std=np.std(arraysum1)
        dis1=mean1-std
        dis2=mean1+std
        j=0
        channel1=[]
        for k in range(len(arraysum1)):
            if (arraysum1[k]<dis1 or arraysum1[k]>dis2) and j<40:
                j=j+1
                sum2.append(arraysum1[k])
                index.append(k)
                channel1.append(arrayofdata50[k])
        while (j<40):
            channel1.append(arrayofdata50[j])
            j=j+1
        arrays.append(channel1)
        arrayofdata=np.array(arrays)
        print(arrayofdata.shape)
    return arrayofdata

In [197]:
arrayofdata=[]

In [198]:
arrayofdata=findchanel(newdata)

(1, 40, 500)
(2, 40, 500)
(3, 40, 500)
(4, 40, 500)
(5, 40, 500)
(6, 40, 500)
(7, 40, 500)
(8, 40, 500)
(9, 40, 500)
(10, 40, 500)
(11, 40, 500)
(12, 40, 500)
(13, 40, 500)
(14, 40, 500)
(15, 40, 500)
(16, 40, 500)
(17, 40, 500)
(18, 40, 500)
(19, 40, 500)
(20, 40, 500)
(21, 40, 500)
(22, 40, 500)
(23, 40, 500)
(24, 40, 500)
(25, 40, 500)
(26, 40, 500)
(27, 40, 500)
(28, 40, 500)
(29, 40, 500)
(30, 40, 500)
(31, 40, 500)
(32, 40, 500)
(33, 40, 500)
(34, 40, 500)
(35, 40, 500)
(36, 40, 500)
(37, 40, 500)
(38, 40, 500)
(39, 40, 500)
(40, 40, 500)
(41, 40, 500)
(42, 40, 500)
(43, 40, 500)
(44, 40, 500)
(45, 40, 500)
(46, 40, 500)
(47, 40, 500)
(48, 40, 500)
(49, 40, 500)
(50, 40, 500)
(51, 40, 500)
(52, 40, 500)
(53, 40, 500)
(54, 40, 500)
(55, 40, 500)
(56, 40, 500)
(57, 40, 500)
(58, 40, 500)
(59, 40, 500)
(60, 40, 500)
(61, 40, 500)
(62, 40, 500)
(63, 40, 500)
(64, 40, 500)
(65, 40, 500)
(66, 40, 500)
(67, 40, 500)
(68, 40, 500)
(69, 40, 500)
(70, 40, 500)
(71, 40, 500)
(72, 40, 500)
(

(556, 40, 500)
(557, 40, 500)
(558, 40, 500)
(559, 40, 500)
(560, 40, 500)
(561, 40, 500)
(562, 40, 500)
(563, 40, 500)
(564, 40, 500)
(565, 40, 500)
(566, 40, 500)
(567, 40, 500)
(568, 40, 500)
(569, 40, 500)
(570, 40, 500)
(571, 40, 500)
(572, 40, 500)
(573, 40, 500)
(574, 40, 500)
(575, 40, 500)
(576, 40, 500)
(577, 40, 500)
(578, 40, 500)
(579, 40, 500)
(580, 40, 500)
(581, 40, 500)
(582, 40, 500)
(583, 40, 500)
(584, 40, 500)
(585, 40, 500)
(586, 40, 500)
(587, 40, 500)
(588, 40, 500)
(589, 40, 500)
(590, 40, 500)
(591, 40, 500)
(592, 40, 500)
(593, 40, 500)
(594, 40, 500)
(595, 40, 500)
(596, 40, 500)
(597, 40, 500)
(598, 40, 500)
(599, 40, 500)
(600, 40, 500)
(601, 40, 500)
(602, 40, 500)
(603, 40, 500)
(604, 40, 500)
(605, 40, 500)
(606, 40, 500)
(607, 40, 500)
(608, 40, 500)
(609, 40, 500)
(610, 40, 500)
(611, 40, 500)
(612, 40, 500)
(613, 40, 500)
(614, 40, 500)
(615, 40, 500)
(616, 40, 500)
(617, 40, 500)
(618, 40, 500)
(619, 40, 500)
(620, 40, 500)
(621, 40, 500)
(622, 40, 

In [87]:
dataof50=[]
for channel in newdata[1]:
    dataof50.append(channel)
arrayofdata50=np.array(dataof50)
print(arrayofdata50.shape)
sum1=[]
for channel in arrayofdata50:
    sum1.append(np.sum(channel))
arraysum1=np.array(sum1)
std1=np.std(arraysum1)
print(std1)
mean1=np.sum(arraysum1)/125
Dev=arraysum1-mean1
SquareofDev=Dev*Dev
sumofdev=np.sum(SquareofDev)
var=sumofdev/125
        #print("variance",var)
std=np.sqrt(var)
print("std",std)

(125, 500)
0.001392250527117299
std 0.001392250527117299


In [190]:
def classify_test_KNN(X,y):

    clf = make_pipeline(Vectorizer(),
                         LogisticRegression())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)
    
    clf.fit(X_train, y_train)
    
    score = clf.score(X_test, y_test)
    
    return score


In [177]:
def get_samples_targets(epochs):
    X = epochs.get_data()
    y = epochs.events[:,-1]
    return X, y

In [178]:
len(epoch.events[:,-1])

968

In [184]:
print(arrayofdata.shape)
X = arrayofdata
y = epoch.events[:,-1]
classify_test_KNN(X,y)

(968, 10, 500)


0.08247422680412371

In [185]:
def filter_event_id(epoch):
    epochs=[[]]
    j=0
    for i in range(len(epoch.events[:,-1])):
        if i % 3 ==0:
            epochs.append([])
            j=j+1
            epochs[j].append(epoch.events[i,-1])
        else:
            epochs[j].append(epoch.events[i,-1])
    for events in epochs:
        if  4 in events or 1 in events or 13 in events or 16 in events:
            for i in range(len(events)):
                    events[i]=4
        else:
            for i in range(len(events)):
                    events[i]=5
    epochs.pop(0)
    flattened_list = [y for x in epochs for y in x]
    for i in range(len(epoch.events)):
        epoch.events[i]=flattened_list[i]
    return epoch

In [186]:
epoch=filter_event_id(epoch)
epoch.events[:,-1]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,

In [199]:
print(arrayofdata.shape)
X = arrayofdata
y = epoch.events[:,-1]
classify_test_KNN(X,y)

(968, 40, 500)


0.5326460481099656

In [233]:
y[0:60]=4

In [241]:
epoch.events[:,-1]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,

In [239]:
y

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,

In [235]:
classify_test_KNN(X,y)

0.7560137457044673