In [374]:
import mne 
import numpy as np
import os
import matplotlib.pyplot as plt

In [238]:
def arrayFiles(path):
    folderContent = os.listdir(path)
    fifFiles = []
    for i in folderContent :
        fifFiles.append(path + "/" + i)
    
    return fifFiles

In [239]:
#concatenate path to name of each file and store in array for reading in data
path = '/Volumes/flash64/EpochedEEG'
allFifFiles = arrayFiles(path)


In [240]:
epoch = mne.read_epochs(allFifFiles[0],preload=True)

Reading /Volumes/flash64/EpochedEEG/20131216_1441_epo.fif ...
    Found the data of interest:
        t =    -199.22 ...     500.00 ms
        0 CTF compensation matrices available
5424 matching events found
Applying baseline correction (mode: mean)
5424 matching events found
Applying baseline correction (mode: mean)
Not setting metadata
0 projection items activated


In [241]:
#see all event ids
epoch.event_id

{'congruent': 133,
 'correct': 129,
 'f_baby': 155,
 'f_bell': 156,
 'f_bird': 157,
 'f_burp': 158,
 'f_dog': 159,
 'f_drum': 160,
 'f_knock': 161,
 'f_laugh': 162,
 'f_phone': 163,
 'f_train': 164,
 'f_water': 165,
 'flanker_stim_1': 1,
 'flanker_stim_10': 10,
 'flanker_stim_11': 11,
 'flanker_stim_12': 12,
 'flanker_stim_2': 2,
 'flanker_stim_3': 3,
 'flanker_stim_4': 4,
 'flanker_stim_5': 5,
 'flanker_stim_6': 6,
 'flanker_stim_7': 7,
 'flanker_stim_8': 8,
 'flanker_stim_9': 9,
 'incongruent': 134,
 'incorrect': 130,
 'left_button': 131,
 'right_button': 132,
 't_baby': 135,
 't_bell': 136,
 't_bird': 137,
 't_burp': 138,
 't_dog': 139,
 't_drum': 140,
 't_knock': 141,
 't_laugh': 142,
 't_phone': 143,
 't_train': 144,
 't_water': 145,
 'target_stim_13': 13,
 'target_stim_14': 14,
 'target_stim_15': 15,
 'target_stim_16': 16,
 'target_stim_17': 17,
 'target_stim_18': 18,
 'target_stim_19': 19,
 'target_stim_20': 20,
 'target_stim_21': 21,
 'target_stim_22': 22,
 'target_stim_23': 23

In [290]:
#seperate all flanker events
f_baby_events = epoch.events[epoch.events[:,-1] == 155]
f_bell_events = epoch.events[epoch.events[:,-1] == 156]
f_bird_events = epoch.events[epoch.events[:,-1] == 157] 
f_burp_events = epoch.events[epoch.events[:,-1] == 158]
f_dog_events = epoch.events[epoch.events[:,-1] == 159] 
f_drum_events = epoch.events[epoch.events[:,-1] == 160]
f_knock_events = epoch.events[epoch.events[:,-1] == 161]
f_laugh_events = epoch.events[epoch.events[:,-1] == 162]
f_phone_events = epoch.events[epoch.events[:,-1] == 163]
f_train_events = epoch.events[epoch.events[:,-1] == 164]
f_water_events = epoch.events[epoch.events[:,-1] == 165]



In [315]:
epoch.events[epoch.events[:,-1]==156]

array([[ 47079,    141,    156],
       [ 49048,      0,    156],
       [ 53539,      0,    156],
       [ 54960,    136,    156],
       [130079,      0,    156],
       [132904,      0,    156],
       [134528,      0,    156],
       [136134,      0,    156],
       [136668,      0,    156],
       [139027,    136,    156],
       [140901,      0,    156],
       [142550,    136,    156],
       [246965,      0,    156],
       [249273,      0,    156],
       [250134,    143,    156],
       [252046,      0,    156],
       [256189,      0,    156],
       [258665,      0,    156],
       [259332,    143,    156],
       [259892,      0,    156],
       [302696,    140,    156],
       [304647,    140,    156],
       [305186,      0,    156],
       [306615,    136,    156],
       [314801,    140,    156],
       [315977,    140,    156],
       [317299,    136,    156],
       [317842,      0,    156],
       [506961,      0,    156],
       [507499,    140,    156],
       [50

In [243]:
#array flankers


In [276]:
#156 or 157 or 158 or 159 or 160 or 161 or 162 or 163 or 164 or 165

epoch.events[:,-1] == (155 or 156)


array([False, False, False, ..., False, False, False])

In [352]:
epoch.events

array([[  2411,      0,    131],
       [  2580,      0,     31],
       [  2581,     31,    144],
       ...,
       [658880,      0,      1],
       [658931,      0,    131],
       [659013,      0,    134]])

In [379]:
''''f_baby': 155,
 'f_bell': 156,
 'f_bird': 157,
 'f_burp': 158,
 'f_dog': 159,
 'f_drum': 160,
 'f_knock': 161,
 'f_laugh': 162,
 'f_phone': 163,
 'f_train': 164,
 'f_water': 165,'''

flankerEpochs = epoch['f_baby','f_bell','f_bird','f_burp','f_dog','f_drum','f_knock',
             'f_laugh','f_phone','f_train','f_water']

targetEpochs = epoch['t_baby','t_bell','t_bird','t_burp','t_dog','t_drum','t_knock',
             't_laugh','t_phone','t_train','t_water']

#targetEpochs.plot(n_channels=20)

flankerTargetEpoch = epoch['f_baby','f_bell','f_bird','f_burp','f_dog','f_drum','f_knock',
             'f_laugh','f_phone','f_train','f_water','t_baby','t_bell','t_bird','t_burp','t_dog','t_drum','t_knock',
             't_laugh','t_phone','t_train','t_water']
flankerTargetEpoch.event_id

{'f_baby': 155,
 'f_bell': 156,
 'f_bird': 157,
 'f_burp': 158,
 'f_dog': 159,
 'f_drum': 160,
 'f_knock': 161,
 'f_laugh': 162,
 'f_phone': 163,
 'f_train': 164,
 'f_water': 165,
 't_baby': 135,
 't_bell': 136,
 't_bird': 137,
 't_burp': 138,
 't_dog': 139,
 't_drum': 140,
 't_knock': 141,
 't_laugh': 142,
 't_phone': 143,
 't_train': 144,
 't_water': 145}

In [323]:
epoch.events[epoch.events[:,-1]==135]

array([[ 59863,     31,    135],
       [ 61043,     31,    135],
       [ 63464,      0,    135],
       [ 64187,     31,    135],
       [ 65746,      0,    135],
       [ 67455,     31,    135],
       [ 68820,     31,    135],
       [ 70082,     31,    135],
       [ 70870,     31,    135],
       [ 72179,     31,    135],
       [181060,      0,    135],
       [182132,      0,    135],
       [183221,     31,    135],
       [184535,      0,    135],
       [185077,     31,    135],
       [188105,      0,    135],
       [189048,      0,    135],
       [190895,     31,    135],
       [193091,     31,    135],
       [194155,     31,    135],
       [231788,      0,    135],
       [234578,     31,    135],
       [236903,     31,    135],
       [237442,      0,    135],
       [238518,     31,    135],
       [239057,    132,    135],
       [240133,     31,    135],
       [242291,      0,    135],
       [242829,     31,    135],
       [243906,      0,    135],
       [35

In [291]:
flankerEpochs = np.concatenate((f_baby_events,f_bell_events,f_bird_events,f_burp_events,
                               f_dog_events,f_drum_events,f_knock_events,f_laugh_events,
                               f_phone_events,f_train_events,f_water_events),axis=0)

In [292]:
#flankerEpochs

array([[181061,    135,    155],
       [182133,    135,    155],
       [183223,      0,    155],
       ...,
       [548211,      0,    165],
       [548990,    137,    165],
       [550734,    145,    165]])

In [293]:
#this only saves event info in arrays NOT the data!
"""
t_baby_events = epoch.events[epoch.events[:,-1] == 135]
t_bell_events = epoch.events[epoch.events[:,-1] == 136]
t_bird_events = epoch.events[epoch.events[:,-1] == 13] 
t_burp_events = epoch.events[epoch.events[:,-1] == 138]
t_dog_events = epoch.events[epoch.events[:,-1] == 139] 
t_drum_events = epoch.events[epoch.events[:,-1] == 140]
t_knock_events = epoch.events[epoch.events[:,-1] == 141]
t_laugh_events = epoch.events[epoch.events[:,-1] == 142]
t_phone_events = epoch.events[epoch.events[:,-1] == 143]
t_train_events = epoch.events[epoch.events[:,-1] == 144]
t_water_events = epoch.events[epoch.events[:,-1] == 145]
"""

In [294]:
#cocatenate the events
"""
targetEpochs = np.concatenate((t_baby_events,t_bell_events,t_bird_events,t_burp_events,
                               t_dog_events,t_drum_events,t_knock_events,t_laugh_events,
                               t_phone_events,t_train_events,t_water_events),axis=0)
"""

In [303]:
#now i have two arrays flanker/target events.
#I want only one array with both flanker and target
"""
flankers_targets = np.concatenate((f_baby_events,f_bell_events,f_bird_events,f_burp_events,
                               f_dog_events,f_drum_events,f_knock_events,f_laugh_events,
                               f_phone_events,f_train_events,f_water_events,t_baby_events,t_bell_events,t_bird_events,t_burp_events,
                               t_dog_events,t_drum_events,t_knock_events,t_laugh_events,
                               t_phone_events,t_train_events,t_water_events),axis=0) """